blog/views/blog.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort

from .auth import login_required
from .db import get_db
from .comment import get_comments
from .tag import get_post_tags

bp = Blueprint('blog', __name__)


def get_posts():
    posts = get_db().execute(
        'SELECT p.id, title, body, created, author_id, username, likes'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' ORDER BY created DESC'
        ).fetchall()

    return posts


def get_post(post_id, check_author=True):
    post = get_db().execute(
        'SELECT p.id, title, body, created, author_id, username, likes'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' WHERE p.id = ?',
        (post_id,)
    ).fetchone()

    if post is None:
        abort(404, f"Post id {post_id} doesn't exist.")

    if check_author and post['author_id'] != g.user['id']:
        abort(403)

    return post


def search_posts_by_title_or_tag(search_term:str):
    db=get_db()
    posts = db.execute(
        'SELECT DISTINCT post.id, title, body, post.created, author_id, username, likes tag_text'
        ' FROM post INNER JOIN user ON post.author_id=user.id INNER JOIN tag ON post.id=tag.post_id'
        ' WHERE LOWER(post.title) LIKE LOWER(?) OR LOWER(tag_text) LIKE LOWER(?)',
        (f'%{search_term}%',f'%{search_term}%',)
    ).fetchall()
    return posts

@bp.route('/',methods=('GET','POST'))
def index():
    if request.method=='GET':
        posts = get_posts()
        return render_template('blog/index.html', posts=posts)
    if request.method=='POST':
        search_term:str = str(request.form['search_term'])
        posts = search_posts_by_title_or_tag(search_term=search_term)
        print(posts)
        return render_template('blog/index.html', posts=posts)
    else:
        return "<p>method not allowed</p>"


@bp.route('/blog/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None
  

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO post (title, body, author_id, likes)'
                ' VALUES (?, ?, ?, ?)',
                (title, body, g.user['id'], 0)
            )
            db.commit()
            print(title)
            print(body)
            print(g.user['id'])
            
            return redirect(url_for('blog.index'))

    return render_template('blog/create.html')


@bp.route('/blog/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    post = get_post(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'UPDATE post SET title = ?, body = ?'
                ' WHERE id = ?',
                (title, body, id)
            )
            db.commit()
            return redirect(url_for('blog.index'))

    return render_template('blog/update.html', post=post)


@bp.route('/blog/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    get_post(id)
    db = get_db()
    db.execute('DELETE FROM post WHERE id = ?', (id,))
    db.commit()
    return redirect(url_for('blog.index'))


@bp.route('/blog/<int:post_id>', methods=('GET',))
def view_single_post(post_id):
    
    post = get_post(post_id,check_author=False)
    comments = get_comments(post_id=post_id)
    tags = get_post_tags(post_id=post_id)

    return render_template('blog/blog.html', post=post, comments=comments, tags=tags)


@bp.route('/api/post', methods=('GET',))
def api_posts():
    posts = get_posts()
    return [dict(post) for post in posts]

@bp.route('/api/post/<int:post_id>', methods=('GET',))
def api_post(post_id):
    post = get_post(post_id=post_id, check_author=False)
    return dict(post)

blog/views/comment.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)

from .auth import login_required
from .db import get_db

bp = Blueprint('comment', __name__)


def get_comments(post_id):

    comments = get_db().execute(
        'SELECT *'
        ' FROM comment JOIN user ON user_id = user.id'
        ' WHERE post_id = ?'
        ' ORDER BY created DESC',
        (post_id,)
    ).fetchall()

    return comments


@bp.route('/<int:post_id>/add_comment', methods=('POST','GET'))
@login_required
def add_comment(post_id):
    title:str = request.form['title']
    body:str = request.form['body']

    db = get_db()
    db.execute(
        'INSERT INTO comment (title, body, user_id, post_id)'
        ' values(?,?,?,?)',
        (title,body,g.user['id'],post_id )

    )
    db.commit()
    return redirect(f"/blog/{post_id}")


@bp.route('/<int:post_id>/delete_comment/<int:comment_id>', methods=('POST','GET'))
@login_required
def delete_comment(comment_id, post_id):

    db = get_db()
    db.execute('DELETE from comment WHERE id=?',(comment_id,)) 
    db.commit()
    return redirect(f"/blog/{post_id}")

blog/views/like.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort

from .auth import login_required
from .db import get_db
from .blog import get_post

bp = Blueprint('like', __name__)


def has_been_liked(post_id) -> bool:
    db = get_db()
    liked = db.execute(
        'SELECT *'
        ' FROM like'
        ' WHERE post_id = ? AND user_id = ?',
        (post_id,g.user['id'])
    ).fetchone()

    if liked is None:
        return False
    return True


@bp.route('/blog/<int:post_id>/like', methods=('GET',))
@login_required
def like_post(post_id):

    if has_been_liked(post_id=post_id):
        flash('Post has already been liked')
        return redirect(f"/blog/{post_id}") 


    post = get_post(post_id,check_author=False) 
    n_likes:int = post['likes']+1
    db = get_db()
    db.execute(
        'INSERT INTO like (post_id, user_id)'
        ' VALUES(?, ?)',(post_id,g.user['id'])
    )
    db.execute(
        'UPDATE post SET likes = ?'
        ' WHERE id = ?',
        (n_likes, post_id)
    )
    db.commit()

    return redirect(f"/blog/{post_id}")


@bp.route('/blog/<int:post_id>/dislike', methods=('GET',))
@login_required
def dislike_post(post_id):

    if has_been_liked(post_id=post_id) == False:
        flash('Post has already been disliked')
        return redirect(f"/blog/{post_id}") 

    post = get_post(post_id,check_author=False) 
    n_likes:int = max(post['likes']-1,0)
    print(n_likes)
    db = get_db()
    db.execute('DELETE from like WHERE post_id=? and user_id=?',(post_id,g.user['id']))
    db.execute(
        'UPDATE post SET likes = ?'
        ' WHERE id = ?',
        (n_likes, post_id)
    )
    db.commit()

    return redirect(f"/blog/{post_id}")

blog/views/tag.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)

from .auth import login_required, owner_of_page, is_owwner_logged
from .db import get_db


bp = Blueprint('tag', __name__)


def get_post_tags(post_id:int):

    tags = get_db().execute(
        'SELECT *'
        ' FROM tag'
        ' WHERE post_id = ?',
        (post_id,)
    ).fetchall()

    return tags


def get_posts_per_tag(tag_text:str):
    posts = get_db().execute(
        'SELECT *'
        ' FROM tag INNER JOIN post ON tag.post_id = post.id INNER JOIN user ON user.id=author_id'
        ' WHERE tag_text=?',
        (tag_text,)
    ).fetchall()
    
    return posts


def get_tags():
    db = get_db()
    tags = db.execute('SELECT  tag_text, COUNT(tag_text) AS count'
            ' FROM tag' 
            ' GROUP BY tag_text',
            ).fetchall()
    return tags


# Routes 

@bp.route('/<int:post_id>/add_tag', methods=('POST',))
@login_required
def add_tag(post_id):

    if is_owwner_logged(post_id=post_id)==False:
        flash('You are not the owner if this post, you can\'t add tags')
        return redirect(f"/blog/{post_id}")
    
    tag_text:str = request.form['tag_text']
    db = get_db()
    db.execute(
        'INSERT INTO tag (tag_text, user_id, post_id)'
        ' values(?,?,?)',
        (tag_text,g.user['id'],post_id )

    )
    db.commit()
    return redirect(f"/blog/{post_id}")


@bp.route('/<int:post_id>/remove_tag/<string:tag_text>', methods=('GET',))
@login_required
def delete_tag(post_id:int, tag_text:str):

    if is_owwner_logged(post_id=post_id)==False:
        flash('You are not the owner if this post. You can\'t delete tags')
        return redirect(f"/blog/{post_id}")
    
    db = get_db()
    db.execute(
        'DELETE from tag WHERE post_id=? AND tag_text=?',(post_id,tag_text)
    )
    db.commit()
    return redirect(f"/blog/{post_id}")



@bp.route('/tag/<string:tag_text>', methods=('GET',))
def show_posts_by_tag(tag_text):
    posts = get_posts_per_tag(tag_text=tag_text)
    print('posts', posts)
    return render_template('tag/list.html', posts=posts, tag_text=tag_text)


@bp.route('/tags', methods=('GET',))
def show_all_tags():
    tags = get_tags()
    return render_template('tag/list_all.html', tags=tags) 




@bp.route('/api/tag', methods=('GET',))
def api_all_tags():
    tags = get_tags()
    tags = [dict(tag) for tag in tags]
    for tag in tags:
        tag['posts'] = [dict(post)['title'] for post in get_posts_per_tag(tag['tag_text'])]
    return tags


@bp.route('/api/tag/<string:tag_text>', methods=('GET',))
def api_posts_per_tag(tag_text):
    posts = get_posts_per_tag(tag_text=tag_text)
    posts = [dict(post) for post in posts]
    return posts

blog/templates/blog/blog.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}{{post['title']}}{% endblock %}</h1>
{% endblock %}

{% block content %}

<article class="post">
    <header>
      <div>
        <div class="about">by <a href="/user/{{post['author_id']}}">{{ post['username'] }}</a> on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        <div class="about">likes:{{ post['likes'] }} </div>
      </div> 
      {% if g.user['id'] == post['author_id'] %}
        <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
      {% endif %}
    </header>
    
      <p class="body">{% filter markdown %}{{ post['body'] }}{% endfilter %}</p>
    
  </article>
  <hr>
  {% if g.user %}
  <a href="{{ url_for('like.like_post', post_id=post['id']) }} ">Like post | </a>
  <a href="{{ url_for('like.dislike_post', post_id=post['id']) }}">Dislike post</a>
  <hr>
  {% endif %}

  <h4>Tags</h4> 
  {% for tag in tags %}
  <label>
    <a href="/tag/{{tag['tag_text']}}">{{tag['tag_text']}}</a>
    <a href="{{ url_for('tag.delete_tag',post_id=post['id'],tag_text=tag['tag_text']) }}" class="danger" style="text-decoration:none"> X </a> <label>|</label>
  </label>
  {% endfor%}

  {% if g.user %}
  <form method="post" action="{{ url_for('tag.add_tag', post_id=post['id']) }}">
    <input name="tag_text" required>
    <input type="submit" value="add tag">
  </form>
  <hr>

  <details name="New Comment"><summary>New comment</summary>
    <form method="post" action="{{ url_for('comment.add_comment', post_id=post['id']) }} ">
      <label for="title">Title</label>
      <input name="title" id="title" value="{{ request.form['title'] }}" required>
      <label for="body">Body</label>
      <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
      <input type="submit" value="Add comment">
    </form>
  </details>
  {% endif %}
  <hr>
  
  <h4>Comments</h4>
  {% for comment in comments%}
    <article class="post">
        <div>{{comment['title']}} </div>
        <div class="about">by {{ comment['username'] }} on {{ comment['created'].strftime('%Y-%m-%d') }}</div>
        <p>{{comment['body']}} </p>
        {% if g.user['id'] == comment['user_id'] %}
            <!-- <a class="action" href="#">Edit</a> -->
            <a class="action" href="{{ url_for('comment.delete_comment', comment_id=comment['id'], post_id=post['id'] ) }} ">Delete comment</a>
        {% endif %}
    </article>
  {% endfor %}
 


{% endblock %}

blog/templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Posts{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  <form method="post">
    <input type="text" name="search_term">
    <input type="submit" value="Search">
  </form>

  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1><a href="/blog/{{post['id']}} ">{{ post['title'] }} </a></h1>
          <div class="about">by <a href="/user/{{post['author_id']}}">{{ post['username'] }}</a> on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
        {% endif %}
      </header>
      <!-- {% if post['body']|length>=150 %}
      <p class="body">{{ post['body'][0:150] }} ...</p>
      {% else %}
      <p class="body">{{ post['body']}}</p>
      {% endif %} -->
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

blog/templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
      value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('blog.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}